### PR TITLE
Hw2_1

### PR DESCRIPTION
**Pull request by screemix**
Implemented ```get_uniport, get_ensemble, parse_response_uniprot, parse_response_ensemble, get_and_parse``` for HW2. 
Waiting for @rinnifox approve.

### CODE REVIEW

**Comment by rinnifox** [comment]
Hi Alla!

Good work, nice that you've also used the error handling! 👍🏻

I have a comment about ENSEMBL regular expression. Your code won't raise an error in case of ID like that `ENSMUSGRANDOMTEXT00000041147`, as you allow to have any amount of literals after `ENS...`. Please, check this [link](https://www.ensembl.org/info/genome/stable_ids/prefixes.htm) and try to modify your rule a little bit. 

There are two main things to note:
- Feature prefix (1 or 2 symbols indicating the type of the sequence);
- Species (nothing for human and a three-letter code for other ones; let's not concentrate on rare mice cases like `MGP_AKRJ_`).

Using this, you should be able to create more precise expression to filter ENSEMBL codes.

And please check your code for typos like `uniport` instead of `uniprot` :)

Fix this please before the next lecture, ok?

**Comment by rinnifox** [comment]
UPD.

> Species (nothing for human and a three-letter code for other ones;

**Comment by screemix** [comment]
@rinnifox fixed, thanks. Should it be ok now?

**Comment by rinnifox** [comment]
Yes, you can merge the PR :)

**Pull request merged**
